[tool.poetry]
name = "argsense"
version = "1.0.0a5"
homepage = "https://github.com/likianta/argsense-cli"
description = "New command line interface based on Python Rich library."
readme = "README.md"
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
pysimplegui = "*"
rich = "*"
textual = "*"

[tool.poetry.scripts]
argsense-cli = 'argsense.__main__:cli'
argsense-gui = 'argsense.__main__:gui'
argsense-tui = 'argsense.__main__:tui'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
