[tool.poetry]
name = "argsense"
version = "0.5.5"
homepage = "https://github.com/likianta/argsense-cli"
description = "New command line interface based on Python Rich library."
readme = "README.md"
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pysimplegui = { version = "*", optional = true }
rich = "*"
# TODO: trogon = "*"
textual = "*"

[tool.poetry.extras]
gui = ["pysimplegui"]  # pip install argsense[gui]

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "default"

[tool.poetry.scripts]
argsense-cli = 'argsense.__main__:cli'
argsense-gui = 'argsense.__main__:gui'
argsense-tui = 'argsense.__main__:tui'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
