[tool.poetry]
name = "argsense"
version = "0.6.0a0"
homepage = "https://github.com/likianta/argsense-cli"
description = "New command line interface based on Rich library."
readme = "README.md"
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
rich = "^13.9.0"

# --- TODO: GUI
pysimplegui = { version = "^5.0.0", optional = true }
#   freesimplegui = "*"
#   pyapp-window = "*"
#   streamlit = "*"
#   textual = "*"
#   trogon = "*"

[tool.poetry.extras]
gui = ["pysimplegui"]  # pip install argsense[gui]

[tool.poetry.group.dev.dependencies]
pyinstrument = "^5.0.0"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[tool.poetry.scripts]
argsense-cli = 'argsense.__main__:cli'
argsense-gui = 'argsense.__main__:gui'
argsense-tui = 'argsense.__main__:tui'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
